<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>13</LangVersion>
		<Nullable>enable</Nullable>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<Platforms>AnyCPU;x64</Platforms>
		<Configurations>Debug;Release;EXILED;LABAPI</Configurations>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'EXILED'">
		<DefineConstants>EXILED</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'LABAPI'">
		<DefineConstants>LABAPI</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ExMod.Exiled" Version="9.14.2" />
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
		<PackageReference Include="Northwood.LabAPI" Version="1.1.7" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>D:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed\Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Assembly-CSharp-firstpass">
			<HintPath>D:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
		</Reference>
		<Reference Include="Mirror">
			<HintPath>D:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed\Mirror.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>D:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
		  <HintPath>D:\Program Files (x86)\Steam\steamapps\common\SCP Secret Laboratory Dedicated Server\SCPSL_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>